[workspace]
members = ["mik32-pac", "mik32-hal"]
resolver = "3"

[profile.dev]
codegen-units = 1
debug = true
lto = true
opt-level = "z"

[profile.release]
codegen-units = 1
debug = true
lto = true
opt-level = "z"
