MEMORY {
    EEPROM : ORIGIN = 0x01000000, LENGTH = 8K
    RAM : ORIGIN = 0x02000000, LENGTH = 16K
    /* SPIFI : ORIGIN = 0x80000000, LENGTH = 2048M */
}

REGION_ALIAS("REGION_TEXT", EEPROM);
REGION_ALIAS("REGION_RODATA", EEPROM);
REGION_ALIAS("REGION_DATA", RAM);
REGION_ALIAS("REGION_BSS", RAM);
REGION_ALIAS("REGION_HEAP", RAM);
REGION_ALIAS("REGION_STACK", RAM);
